import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";


export const metadata: Metadata = {
  title: "Meals App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,//funkciayi mutq ekav children drec bodi mej
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
